sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t clevins/ci-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true clevins/ci-test npm run test

after_success:
  - docker build -t clevins/pg-at-client ./client
  - docker build -t clevins/pg-at-strapi ./strapi
  - docker build -t clevins/pg-at-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push clevins/pg-at-client
  - docker push clevins/pg-at-strapi
  - docker push clevins/pg-at-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "pg-at"
  env: "pg-at-env"
  bucket_name: "elasticbeanstalk-eu-west-1-800939509044"
  bucket_path: "pg-at"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
