version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    image: clevins/pg-at-client
    environment:
      API_BASE_URL: ${API_BASE_URL}
    volumes:
      - /app/node_modules
      - ./client:/usr/src/app
    ports:
      - 49153:49153
  strapi:
    build:
      dockerfile: Dockerfile.dev
      context: ./strapi
    image: clevins/pg-at-strapi
    volumes:
      - /app/node_modules
      - ./strapi:/app
    env_file: .env
    environment:
      TZ: "Europe/Dublin"
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URI: ${DATABASE_URI}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SRV: ${DATABASE_SRV}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
  nginx:
    restart: always
    image: clevins/pg-at-nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - client
      - strapi
    ports:
      - "3011:80"
      - "3012:85"
